### ISSUE TITLE
Add checks to allow merging of pull requests.

### ISSUE THREAD

**Issue by curquhart** [curquhart/ddcp#7]
- [x] add pipeline types (Codepipeline and CloudWatch) since Codepipeline can't run on arbitrary branches (#18)
- [x] consume GitHub pr events and mirror to github_pr_pr# branch. (#19) 
- [x] send all CodeBuild statuses to sns (#20)
- [x] consume CodeBuild statuses from sns, resolve to branch, infer pr# from branch name, send status to github (#21)

* The github bits of this are only for this project with minimal abstraction (poc)... #1 should make this a generally supported feature.
